ALTER TABLE `device_info`
ADD COLUMN `time_zone` VARCHAR(30) DEFAULT NULL,
ADD COLUMN `bioData_Stamp` VARCHAR(30) DEFAULT NULL,
ADD COLUMN `idCard_Stamp` VARCHAR(30) DEFAULT NULL,
ADD COLUMN `errorLog_Stamp` VARCHAR(30) DEFAULT NULL;
